---
title: "Hypothesis 3"
author:  "Mofi Islam and Dennis Wollersheim "
date: "2018-04-30"
output: 
  word_document:
    reference_docx: ../../common/word_reference_style.docx
  html_document:
    code_folding: hide
---


```{r set-options, echo=FALSE, cache=FALSE, warning=FALSE, results='hide'}
rm(list=ls())
options(width = 200)
show_code = FALSE
source("lib/functions.R")
source("lib/standardisation.R")
source("lib/get_data.R")
source("lib/generate_data_frames.R")

df_mapdata = read.csv('data/Data2MapFromMofi.csv') %>% as.tibble()

```
#Methods

```{r data_preparation, echo=FALSE, cache=FALSE, results="hide", warning=FALSE}

data.cache( generate_data_frames, frequency='yearly')

```

maps 

```{r}


df_mapdata  %>%
  rename( lga=LGA ) %>%
  mutate( lga = as.character( lga ) ) %>%
  filter( Desc == 'Years_Regular') %>% 
  printMap( title = "Number Years\nRegular users\nin highest\nquartile DDD ",
                                                filename = '/tmp/regular.png' )

#
df_mapdata  %>%
  rename( lga=LGA ) %>%
  mutate( lga = as.character( lga ) ) %>%
  filter( Desc == 'Years_fourth_quartile') %>% 
  printMap( title = "Years\ntotal qty in\nfourth quartile",
           filename = '/tmp/fourthQuartile.png' )


debug( printMap)

printMap = function( df, title, filename )  {


  vp_sydney=viewport(x= .55, y= .5, width= 0.2, height= 0.2)
  vp_melbourne=viewport(x= 0.24, y= 0.15, width= 0.2, height= 0.2)
  vp_legend=viewport(x= 0.75, y= 0.82, width= 0.3, height= 0.3)
  bbox_oz = c( 140.9617 , -39.15839 , 159.1054 , -28.15702 )

  right_join( df, df_population %>% distinct( lga ) ) %>%
      mutate( value = ifelse( is.na(Value), NA, Value )) %>%
      select( lga, value ) %>%
      rbind( data.frame( lga=c(89399), value=NA)) %>%
      mutate( value=as.ordered(value)) %>% 
      select( lga, value ) %>%
      append_data( base_map, 
                  ., 
                  key.shp="LGA_CODE11", 
                  key.data="lga" 
                  )  %>%
      {.} -> df

  df %>%
    tm_shape( ) + 
    tm_polygons( "value", 
                title = title,
                showNA=FALSE,
                colorNA='#FFFFFF'
                ) +
  tm_layout(frame=FALSE,
            legend.position = c("right", "top"), bg.color="lightgreen",
            inner.margins = c(.25,.02,.02,.25),  # how far in from the bottom and right side (for insets)
            legend.show=FALSE) %>%
  {.} -> map

  print(map)

  df %>%
    tm_shape( ) + 
    tm_polygons( "value", 
                title = title,
                showNA=FALSE,
                colorNA='#FFFFFF'
                ) +
  tm_layout(frame=FALSE,
            bg.color="lightgreen",
            legend.only=TRUE) %>%
    { . } -> m_legend

  print(m_legend, vp=vp_legend)

  df %>%
    tm_shape( xlim=get_state_capital_xlim(2),
              ylim=get_state_capital_ylim(2) ) +
    tm_polygons( "value", 
                showNA=FALSE,
                colorNA='#FFFFFF',
                legend.show=FALSE) +
    tm_layout(frame=FALSE, 
              bg.color="lightgreen"
              )  %>%
    {.} -> m_melbourne

  df %>% 
    tm_shape( xlim=get_state_capital_xlim(1),
              ylim=get_state_capital_ylim(1) ) +
    tm_polygons( "value", 
      showNA=FALSE,
      colorNA='#FFFFFF',
      legend.show=FALSE) +
    tm_layout(frame=FALSE, bg.color="lightgreen")  %>%
    {.} -> m_sydney

  # print insets
  print(m_sydney, vp=vp_sydney)
  print(m_melbourne, vp=vp_melbourne)
  save_tmap( map, 
            insets_vp = list( vp_sydney, vp_melbourne, vp_legend ),
            insets_tm = list( m_sydney, m_melbourne, m_legend ),
            filename=filename, 
             width=1100, height=1080, asp=0
            ) 
}


    

```

